### ISSUE TITLE
Not working at all in 1.21 [fabric] :(

### ISSUE THREAD

**Issue by modyreso20111** [MrCrayfish/Configured#151]
It doesn't work at all only mods with configure menu opens other mods don't

**Comment by FoilGear** [comment]
<strike>experiencing same issue. version 1.21.1</strike>
The minor version of '1.21 **.1**' was aimed primarily at server owners, with most mod authors opting to not update to this minor version (yet) as compatibility is not broken between clients on 1.21 and servers on 1.21.1.
After downgrading to just '1.21', Configured seems to work for me, now.

**Comment by nothere333** [comment]
Fabric 1.20.1 dooesn't work at all for me
I tried and without modmenu thinking it might be the issue but no luck, No Mod option shows up
edit: With the Mod menu In the list it says Configured is there, And also Keybind setting shows up but it doesn't open

**Comment by MrCrayfish** [comment]
Configured only works with supported configuration libraries. Most mods on NeoForge all use the same built in configuration library provided by NeoForge. This is why Configured works well on NeoForge and will show a config screen for almost all mods. On Fabric, it's a free for all. Every mod uses either a community library or their own in-house solution. This makes it really difficult and a maintenance nightmare since their are so many different libraries and solutions, when compared to NeoForge, I only need to support one. This is why you may think Configured is "not working"

As of right now, Configured only supports Framework and JEI configs on Fabric. I have looked at other libraries, but they seem to add their own GUI solution for developers that depend on them, so no point for Configured.

**Comment by modyreso20111** [comment]
So that's why I get it no one has time to code for each library a support for configured well it's up to the libraries' creators to add a support for the configured mod
