### ISSUE TITLE
Configured causes crash if `config` folder is a symlink

### ISSUE THREAD

**Issue by dithpri** [MrCrayfish/Configured#50]
The `config` folder being a symlink works just fine for minecraft & forge.
However, if Configured is installed, the game crashes when loading.
In the crash report below, `/home/user/minecraft-instances/configuredbug/config` is a symlink to `/home/user/Documents/test-modpack/overrides/config`
***
[crash-client.txt](https://github.com/MrCrayfish/Configured/files/8749814/crash-client.txt)

**Comment by MrCrayfish** [comment]
I can't seem find anything in the logs related to my mod. I have looked into the code related to the stacktrace and it's saying that symlinks aren't allowed. Is the directory you have linked already created? Does it happen for other mods that have a config (without Configured)?

**Comment by Speiger** [comment]
> The `config` folder being a symlink works just fine for minecraft & forge.
> However, if Configured is installed, the game crashes when loading.
> In the crash report below, `/home/user/minecraft-instances/configuredbug/config` is a symlink to `/home/user/Documents/test-modpack/overrides/config`

Eh to provide some expertise, though i am not that deep into it, java does support Symlinks, but you actually have to tell it to account for it, or check for it.
Since it is not commonplace, minecraft/forge configs are not really symlink compatible from my knowledge.

This is not a @MrCrayfish bug, but a Forge bug in this case. Because Forge manages the configs backend while crayfish only interacts with it. So he has 0 control over said implementation.

**Comment by MrCrayfish** [comment]
Closing since this is a Forge is responible for loading configs/generating directories. Again, symlinks are not allowed based on the code.
