### ISSUE TITLE
1.18.2 - opening up JEI configuration through the button fails to find client settings

### ISSUE THREAD

**Issue by nanonestor** [MrCrayfish/Configured#68]
Forge 40.1.73
JEI 10.1.3.240
Configured 1.5.3-1.18.2

In-game button of the JEI mod brings up a screen showing only jei-server.toml.  This screen is generated by Configured.  It for whatever reason does not show jei-client.toml.

**Comment by InFuRiTy** [comment]
Same issues occur in ATM 8 and Inclusive 2 modpacks, both being in 1.19.2
Multiple mods have just a blank config page or server configs only available to them.
It's really a big pain having to relaunch a pack just to change something every time!!

**Comment by RedstoneGamer123** [comment]
Downgrade to the 9. version and it will be fixed

**Comment by MrCrayfish** [comment]
JEI changed their config system, due to creating a Fabric version. They have now moved to a config system that can be used for both loaders, which means it would no longer work. However, if you update to 2.1.0 on 1.19.3 you can use it again. I can't fix on anything lower since the API needed in JEI is only available in 1.19.3 or higher.
